blank_issues_enabled: false
contact_links:
  - name: Community Support
    url: https://discord.studioarchetype.net
    about: If you dont have a bug to report, you can get general and specific support for shutter in our community discord server.
